spring:
  application:
    name: ArgusAPI

  datasource:
    url: jdbc:mysql://localhost:3306/argus_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: db123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
